app:
  name: customers
  namespace: customers-{{ gitea_customize_lab_username }}
  cluster: {{ gitea_customize_apps_subdomain }}

git:
  branch: master
  repo: {{ gitea_customize_gitea_server }}/{{ gitea_customize_lab_username }}/env-gitops.git
  org: development
  name: env-gitops
  host: {{ gitea_customize_gitea_server }}
  token: ''
  webhookSecret: ''
  verify_commits: disabled

lab:
  username: {{ gitea_customize_lab_username }}

image:
  registry: Quay
  organization: quayadmin
  host: {{ gitea_customize_quay_server }}
  name: customers
  tag: v1
