apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.name }}-start-lab
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 100

  template:
    spec:
      restartPolicy: Never
      containers:
      - name: start-lab
        image: registry.redhat.io/openshift4/ose-tools-rhel9@sha256:8037187950e7374a9c9bec4996033c9b24ce374920ef29047d4f63b4c20f3e6b
        command:
          - /bin/bash
          - '-c'
          - |
            while true

            do

              HOST=$(oc get route {{ .Values.lab.username }}-customers-manifests -n customers-{{ .Values.lab.username }} --ignore-not-found --no-headers --output json | jq -r '.spec.host')

              if [ ! -z "${HOST}" ]; then

                STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://${HOST}/customers)

                if [ "${STATUS_CODE}" == "200" ]; then

                  echo 'Endpoint ready.  Initiating remote call...'

                  BASTION_SUBDOMAIN=$(echo {{ .Values.app.cluster }} | sed -r 's/([^.]*.){3}//')

                  curl -kv https://${HOST}/JKHGFTGTYU/bastion.$BASTION_SUBDOMAIN

                  break

                fi

              fi

              echo 'Endpoint not ready...'

              sleep 10

            done
      serviceAccount: job-runner
