kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.app.name }}-{{ .Values.lab.username }}-jobrunner-edit
subjects:
  - kind: ServiceAccount
    name: job-runner
    namespace: {{ .Values.app.name }}-{{ .Values.lab.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
