kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.lab.username }}-ns-rolebinding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.lab.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
